修复部分Bug
Hellobaka/KunBot pull request #3
Opened 2024-10-06 07:14 UTC by KuDikan

- 修复买蛋成功时金币显示数量错误
- 体重达上限时拒绝喂养
- 修改 `GetLevelWeightLimit` 方法返回值为 `double` 类型
- 修复指令解析异常

2024-10-06 07:17 UTC, Hellobaka commented
感谢你的pr，我需要再过一段时间才能查看修改

2024-10-08 05:18 UTC, Hellobaka requested changes

2024-10-08 05:18 UTC, Hellobaka commented on me.cqp.luohuaming.iKun.Code/OrderFunctions/Attack.cs
为什么要这么改，原方法有bug吗

2024-10-08 05:18 UTC, Hellobaka commented on me.cqp.luohuaming.iKun.Code/OrderFunctions/Feed.cs
喂养细节逻辑请在Kun基类进行，不要修改指令解析部分

2024-10-08 05:18 UTC, Hellobaka commented on me.cqp.luohuaming.iKun.Code/OrderFunctions/BuyEgg.cs
不要多次查询数据库，所有操作带锁的，请从上下文计算结果

2024-10-08 10:12 UTC, KuDikan commented on me.cqp.luohuaming.iKun.Code/OrderFunctions/Attack.cs
原方法中`Replace`会替换掉所有指令，改后只替换开头指令。
如指令为`#孵蛋`，那么`#孵蛋0#孵蛋1#孵蛋0#孵蛋`也会被原方法解析。
极端一点，如指令为纯数字则会造成解析异常。

2024-10-08 10:35 UTC, Hellobaka commented on me.cqp.luohuaming.iKun.Code/OrderFunctions/BuyEgg.cs
OK是我看错了

2024-10-08 10:36 UTC, Hellobaka commented on me.cqp.luohuaming.iKun.Code/OrderFunctions/Attack.cs
使用Substring吧

2024-10-08 10:37 UTC, Hellobaka commented
由于我后续又推了一些更改，现在这个PR无法被自动合并，请同步分支之后我再来合并。

2024-10-08 11:06 UTC, closed without merging